import { describe, it, expect } from 'vitest'
import { createPrivateKey, createPublicKey, createSign, createVerify } from 'node:crypto'
import {
  generateAllSecrets,
  generateRsaPrivateKeyB64,
  generateSecretFor,
  KEYPAIR_SECRET_KEYS,
  SECRET_KEYS,
} from '../../src/services/generators/secret-generator.js'

/**
 * AUTH_PRIVATE_KEY provisions jarvis-auth's RS256 signing key. It has to be
 * generated by the installer (nobody should be running openssl by hand), it has
 * to survive an upgrade, and it has to be a *usable* RSA key rather than a
 * plausible-looking string — a hex secret in this slot would fail only later, at
 * the first RS256 mint.
 */
describe('AUTH_PRIVATE_KEY provisioning', () => {
  it('is generated as part of a normal install', () => {
    const secrets = generateAllSecrets()
    expect(secrets.AUTH_PRIVATE_KEY).toBeTruthy()
  })

  it('is listed in SECRET_KEYS so upgrades preserve it', () => {
    // Regenerating this on upgrade would invalidate every live RS256 token and
    // strand verifiers that cache the public key for their process lifetime.
    expect(SECRET_KEYS).toContain('AUTH_PRIVATE_KEY')
  })

  it('is NOT generated as a flat hex secret', () => {
    const secrets = generateAllSecrets()
    expect(secrets.AUTH_PRIVATE_KEY).not.toMatch(/^[0-9a-f]{64}$/)
    expect(KEYPAIR_SECRET_KEYS).toContain('AUTH_PRIVATE_KEY')
  })

  it('decodes from base64 to a PKCS#8 PEM', () => {
    const pem = Buffer.from(generateRsaPrivateKeyB64(), 'base64').toString('utf8')
    expect(pem).toContain('-----BEGIN PRIVATE KEY-----')
    expect(pem).toContain('-----END PRIVATE KEY-----')
  })

  it('is single-line, so .env and compose env blocks cannot mangle it', () => {
    expect(generateRsaPrivateKeyB64()).not.toContain('\n')
  })

  it('produces a genuinely usable 2048-bit RSA signing key', () => {
    const pem = Buffer.from(generateRsaPrivateKeyB64(), 'base64').toString('utf8')
    const key = createPrivateKey(pem)

    expect(key.asymmetricKeyType).toBe('rsa')
    expect(key.asymmetricKeyDetails?.modulusLength).toBe(2048)

    // Round-trip a signature the way jarvis-auth will: sign with the private
    // key, verify with the public half derived from it.
    const data = Buffer.from('jarvis-auth rs256 round trip')
    const signature = createSign('RSA-SHA256').update(data).sign(key)
    const derivedPublic = createPublicKey(key)
    expect(createVerify('RSA-SHA256').update(data).verify(derivedPublic, signature)).toBe(true)
  })

  it('generates a fresh key each time', () => {
    expect(generateRsaPrivateKeyB64()).not.toBe(generateRsaPrivateKeyB64())
  })

  it('leaves ordinary hex secrets alone', () => {
    expect(generateSecretFor('MODEL_SERVICE_TOKEN')).toMatch(/^[0-9a-f]{64}$/)
    expect(generateSecretFor('REDIS_PASSWORD')).toMatch(/^[0-9a-f]{32}$/)
  })
})
