import type { WizardState } from '../../types/wizard.js'
import type { ServiceRegistry } from '../../types/service-registry.js'
import {
  getCoreServices,
  getRecommendedServices,
  getOptionalServices,
  getRequiredInfrastructure,
} from './service-registry.js'
import { serviceIdToPortVar } from './port-utils.js'
import { SECRET_KEYS, generateHexSecret } from './secret-generator.js'

export function generateEnv(state: WizardState, registry: ServiceRegistry): string {
  const lines: string[] = []

  lines.push('# Jarvis Configuration')
  lines.push('# Generated by Jarvis Admin')
  lines.push('')

  // Secrets
  lines.push('# --- Secrets ---')
  for (const key of SECRET_KEYS) {
    // Never emit an empty secret: with JARVIS_ENV=production the boot-time secret
    // guard would refuse to start. A reconstructed install carries its existing
    // value through; a genuinely missing one gets a fresh strong secret (passwords
    // 16 bytes, tokens/keys 32 — matching generateAllSecrets).
    const value = state.secrets[key] || generateHexSecret(key.includes('PASSWORD') ? 16 : 32)
    lines.push(`${key}=${value}`)
  }
  lines.push('')

  // Database
  lines.push('# --- Database ---')
  lines.push(`DB_USER=${state.dbUser}`)
  lines.push('')

  // Service ports
  const coreServices = getCoreServices(registry)
  const enabledRecommended = getRecommendedServices(registry).filter((s) =>
    state.enabledModules.includes(s.id),
  )
  const enabledOptional = getOptionalServices(registry).filter((s) =>
    state.enabledModules.includes(s.id),
  )
  const allEnabled = [...coreServices, ...enabledRecommended, ...enabledOptional]

  lines.push('# --- Service Ports ---')
  for (const svc of allEnabled) {
    const portVar = serviceIdToPortVar(svc.id)
    // admin's containerized backend (SPA + API + /health) serves on 7711, not
    // the registry's nominal 7710 (that's its local redirect target). Keep
    // ADMIN_PORT in lockstep with the compose generator so the published host
    // port lands on 7711. See generateServiceBlock's `effectivePort`.
    const defaultPort = svc.id === 'jarvis-admin' ? 7711 : svc.port
    const port = state.portOverrides[svc.id] ?? defaultPort
    lines.push(`${portVar}=${port}`)
  }
  lines.push('')

  // Infrastructure ports
  const enabledIds = allEnabled.map((s) => s.id)
  const infra = getRequiredInfrastructure(registry, enabledIds)

  // Always include redis
  const redis = registry.infrastructure.find((i) => i.id === 'redis')
  if (redis && !infra.some((i) => i.id === 'redis')) {
    infra.push(redis)
  }

  // Include grafana if loki is present
  const hasLoki = infra.some((i) => i.id === 'loki')
  const grafana = registry.infrastructure.find((i) => i.id === 'grafana')
  if (hasLoki && grafana && !infra.some((i) => i.id === 'grafana')) {
    infra.push(grafana)
  }

  lines.push('# --- Infrastructure Ports ---')
  for (const inf of infra) {
    const portVar = serviceIdToPortVar(inf.id)
    const port = state.infraPortOverrides[inf.id] ?? inf.port
    lines.push(`${portVar}=${port}`)
  }
  lines.push('')

  // Remote LLM/Whisper URLs
  if (state.deploymentMode === 'remote-llm') {
    lines.push('# --- Remote Services ---')
    if (state.remoteLlmUrl) {
      lines.push(`JARVIS_LLM_PROXY_URL=${state.remoteLlmUrl}`)
    }
    if (state.remoteWhisperUrl) {
      lines.push(`JARVIS_WHISPER_URL=${state.remoteWhisperUrl}`)
    }
    lines.push('')
  }

  // Jarvis Relay
  if (state.relayEnabled) {
    lines.push('# --- Jarvis Relay ---')
    lines.push(`JARVIS_RELAY_URL=${state.relayUrl || 'https://relay.jarvisautomation.io'}`)
    // Household JWT consumed by jarvis-notifications to authenticate to the
    // relay's /v1/send. Empty placeholder on first install — the user pastes
    // their household JWT here; reconcile preserves the value via mergeEnv.
    lines.push(`JARVIS_RELAY_HOUSEHOLD_JWT=${state.relayHouseholdJwt ?? ''}`)
    lines.push('')
  }

  // Models directory (absolute HOST path, for admin-in-docker reconciles).
  // Without this, the compose's `${MODELS_DIR:-./.models}` resolves relative
  // to the admin container's working dir (/host/compose/.models), which the
  // docker daemon then binds to a non-existent host path → empty /app/.models
  // → llm-proxy's model_service crashes on startup.
  if (state.hostComposePath) {
    const root = state.hostComposePath.replace(/\/$/, '')
    lines.push('# --- Host paths for admin-in-docker binds ---')
    lines.push(`MODELS_DIR=${root}/.models`)
    // Whisper models dir: same docker-out-of-docker bind-resolution problem.
    // The compose uses `${WHISPER_MODELS_DIR:-./whisper-models}` so a native
    // install still gets the relative-path behavior; admin-in-docker fills
    // the env var with the absolute host path. Prod incident 2026-06-10:
    // the daemon resolved `./whisper-models` against /host/compose, created
    // an empty dir there, and whisper-api silently loaded a NULL model
    // (pywhispercpp's download_model returns None on a path-shaped input).
    lines.push(`WHISPER_MODELS_DIR=${root}/whisper-models`)
    // Same class for postgres' init-db.sh and go2rtc's config — both are
    // file binds; without an absolute host path the daemon creates empty
    // directories at /host/compose/init-db.sh and /host/compose/go2rtc.yaml,
    // postgres skips init (silent, because /docker-entrypoint-initdb.d
    // scans for *files*), and go2rtc fails to read its config.
    lines.push(`INIT_DB_PATH=${root}/init-db.sh`)
    lines.push(`GO2RTC_CONFIG_PATH=${root}/go2rtc.yaml`)
    lines.push('')
  }

  // Release Track
  lines.push('# --- Release Track ---')
  lines.push(`JARVIS_IMAGE_TAG=${state.releaseTrack === 'dev' ? 'dev' : 'latest'}`)
  lines.push('')

  // Whisper backend (image variant: cpu default, or cuda/vulkan/rocm). The
  // compose pins the whisper image by digest, so this env key is the ONLY
  // durable record of the selection — state-reconstructor reads it back on
  // reconcile. Without it, a regenerate silently swaps a GPU whisper for the
  // CPU image (prod 2026-07-04: STT went ~90ms → ~16s).
  lines.push('# --- Whisper Backend ---')
  lines.push(`WHISPER_BACKEND=${state.whisperBackend ?? 'cpu'}`)
  lines.push('')

  // TTS device — same persistence rationale as WHISPER_BACKEND. TTS_GPU_DEVICE
  // pins the single GPU the container may reserve (operators re-pin when GPU0
  // is already full of LLM+whisper — prod 2026-07-05); compose defaults to 0.
  // Image pinning policy — read back by state-reconstructor so reconciles
  // respect it. Default false: floating tags, `docker compose pull` updates.
  lines.push('# --- Image Pinning (opt-in supply-chain hardening) ---')
  lines.push(`PIN_IMAGES=${state.pinImages ? 'true' : 'false'}`)
  lines.push('')

  lines.push('# --- TTS Backend ---')
  lines.push(`TTS_BACKEND=${state.ttsBackend ?? 'cpu'}`)
  if ((state.ttsBackend ?? 'cpu') === 'cuda') {
    lines.push('TTS_GPU_DEVICE=0')
  }
  lines.push('')

  // MQTT broker lock. Fresh installs lock the broker from the first boot
  // (allow_anonymous=false): the command-center reads MQTT_PASSWORD from its
  // env and every node fetches broker creds over authenticated HTTP *before* it
  // ever opens an MQTT connection, so there's no anonymous client to strand.
  // The transition window (true) is reserved for in-place UPGRADES of fleets
  // whose nodes predate credential auto-fetch — handled in the compose-upgrader,
  // not here. Compose still defaults `${MQTT_ALLOW_ANON:-true}` as a safety
  // fallback if this line is ever missing.
  lines.push('# --- MQTT Broker ---')
  lines.push('MQTT_ALLOW_ANON=false')
  lines.push('')

  // Native services (macOS only). Comma-separated list of service IDs the user
  // opted to run as LaunchAgents instead of in Docker. Read back by
  // state-reconstructor so reconcile flows keep them out of compose.
  if (state.nativeServices && state.nativeServices.length > 0) {
    lines.push('# --- Native Services (macOS) ---')
    lines.push(`JARVIS_NATIVE_SERVICES=${state.nativeServices.join(',')}`)
    lines.push('')
  }

  // Host platform — admin runs in Docker, so process.platform inside the
  // container is always 'linux'. The wizard knows the host platform from the
  // first-boot native install; persist it so admin (in Docker) can read it
  // back via HOST_OS and gate the native-services UI correctly.
  lines.push('# --- Host platform ---')
  lines.push(`HOST_OS=${state.platform}`)
  lines.push('')

  // App-to-app auth placeholders (filled after service registration)
  lines.push('# --- App-to-App Auth (populated after registration) ---')
  for (const svc of allEnabled) {
    const suffix = svc.id.replace(/^jarvis-/, '').replace(/-/g, '_').toUpperCase()
    lines.push(`JARVIS_APP_ID_${suffix}=`)
    lines.push(`JARVIS_APP_KEY_${suffix}=`)
  }
  lines.push('')

  return lines.join('\n')
}
